# Generated by Django 5.2.7 on 2025-12-07 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_payment_method_order_session_key_and_more"),
        ("products", "0003_product_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Комментарий клиента к заказу.",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email клиента для уведомлений.",
                max_length=254,
                null=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="ФИО клиента, оформившего заказ.",
                max_length=255,
                null=True,
                verbose_name="ФИО",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличными при получении"),
                    ("card", "Банковская карта"),
                ],
                default="cash",
                help_text="Выбранный клиентом способ оплаты.",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Контактный телефон клиента.",
                max_length=32,
                null=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Session Key гостевого пользователя для привязки заказа.",
                max_length=40,
                null=True,
                verbose_name="Session Key",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(
                blank=True,
                help_text="Адрес, по которому необходимо доставить заказ.",
                null=True,
                verbose_name="Адрес доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачено"),
                    ("shipped", "Отправлено"),
                    ("delivered", "Доставлено"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                help_text="Текущий статус заказа.",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Полная стоимость заказа (фиксируется при оформлении).",
                max_digits=10,
                verbose_name="Полная стоимость",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, оформивший заказ (необязательно для гостей).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                help_text="Заказ, к которому относится данная товарная позиция.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена товара на момент оформления заказа (snapshot).",
                max_digits=10,
                verbose_name="Цена на момент покупки",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                help_text="Товар, который был куплен.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Количество единиц товара в заказе.",
                verbose_name="Количество",
            ),
        ),
    ]
